from django.db import models

# Create your models here.
class Drug(models.Model):
    drugname = models.CharField(max_length=30, verbose_name="Drug Name")
    isopiod = models.BooleanField(default=False, verbose_name="Is Opioid?")

    class Meta:
        db_table = "pd_drugs"

    def __str__(self):
        return (self.drugname)

class Prescriber(models.Model):
    fname = models.CharField(max_length=11, verbose_name="First Name")
    lname = models.CharField(max_length=11, verbose_name="Last Name")
    gender = models.CharField(max_length=2)
    state = models.CharField(max_length=2)
    credentials = models.CharField(max_length=20)
    specialty = models.CharField(max_length=62)
    isopioidprescriber = models.CharField(max_length=5, verbose_name="Is Opioid Prescriber?")
    totalprescriptions = models.IntegerField(default=0, verbose_name="Total Prescriptions")
    abilify = models.IntegerField(default=0)
    acetaminophencodeine = models.IntegerField(default=0)
    acyclovir = models.IntegerField(default=0)
    advairdiskus = models.IntegerField(default=0)
    aggrenox = models.IntegerField(default=0)
    alendronatesodium = models.IntegerField(default=0)
    allopurinol = models.IntegerField(default=0)
    alprazolam = models.IntegerField(default=0)
    amiodaronehcl = models.IntegerField(default=0)
    amitriptylinehcl = models.IntegerField(default=0)
    amlodipinebesylate = models.IntegerField(default=0)
    amlodipinebesylatebenazepril = models.IntegerField(default=0)
    amoxicillin = models.IntegerField(default=0)
    amoxtrpotassiumclavulanate = models.IntegerField(default=0)
    amphetaminesaltcombo = models.IntegerField(default=0)
    atenolol = models.IntegerField(default=0)
    atorvastatincalcium = models.IntegerField(default=0)
    avodart = models.IntegerField(default=0)
    azithromycin = models.IntegerField(default=0)
    baclofen = models.IntegerField(default=0)
    bdultrafinepenneedle = models.IntegerField(default=0)
    benazeprilhcl = models.IntegerField(default=0)
    benicar = models.IntegerField(default=0)
    benicarhct = models.IntegerField(default=0)
    benztropinemesylate = models.IntegerField(default=0)
    bisoprololhydrochlorothiazide = models.IntegerField(default=0)
    brimonidinetartrate = models.IntegerField(default=0)
    bumetanide = models.IntegerField(default=0)
    bupropionhclsr = models.IntegerField(default=0)
    bupropionxl = models.IntegerField(default=0)
    buspironehcl = models.IntegerField(default=0)
    bystolic = models.IntegerField(default=0)
    carbamazepine = models.IntegerField(default=0)
    carbidopalevodopa = models.IntegerField(default=0)
    carisoprodol = models.IntegerField(default=0)
    cartiaxt = models.IntegerField(default=0)
    carvedilol = models.IntegerField(default=0)
    cefuroxime = models.IntegerField(default=0)
    celebrex = models.IntegerField(default=0)
    cephalexin = models.IntegerField(default=0)
    chlorhexidinegluconate = models.IntegerField(default=0)
    chlorthalidone = models.IntegerField(default=0)
    cilostazol = models.IntegerField(default=0)
    ciprofloxacinhcl = models.IntegerField(default=0)
    citalopramhbr = models.IntegerField(default=0)
    clindamycinhcl = models.IntegerField(default=0)
    clobetasolpropionate = models.IntegerField(default=0)
    clonazepam = models.IntegerField(default=0)
    clonidinehcl = models.IntegerField(default=0)
    clopidogrel = models.IntegerField(default=0)
    clotrimazolebetamethasone = models.IntegerField(default=0)
    colcrys = models.IntegerField(default=0)
    combiventrespimat = models.IntegerField(default=0)
    crestor = models.IntegerField(default=0)
    cyclobenzaprinehcl = models.IntegerField(default=0)
    dexilant = models.IntegerField(default=0)
    diazepam = models.IntegerField(default=0)
    diclofenacsodium = models.IntegerField(default=0)
    dicyclominehcl = models.IntegerField(default=0)
    digox = models.IntegerField(default=0)
    digoxin = models.IntegerField(default=0)
    diltiazem24hrcd = models.IntegerField(default=0)
    diltiazem24hrer = models.IntegerField(default=0)
    diltiazemer = models.IntegerField(default=0)
    diltiazemhcl = models.IntegerField(default=0)
    diovan = models.IntegerField(default=0)
    diphenoxylateatropine = models.IntegerField(default=0)
    divalproexsodium = models.IntegerField(default=0)
    divalproexsodiumer = models.IntegerField(default=0)
    donepezilhcl = models.IntegerField(default=0)
    dorzolamidetimolol = models.IntegerField(default=0)
    doxazosinmesylate = models.IntegerField(default=0)
    doxepinhcl = models.IntegerField(default=0)
    doxycyclinehyclate = models.IntegerField(default=0)
    duloxetinehcl = models.IntegerField(default=0)
    enalaprilmaleate = models.IntegerField(default=0)
    escitalopramoxalate = models.IntegerField(default=0)
    estradiol = models.IntegerField(default=0)
    exelon = models.IntegerField(default=0)
    famotidine = models.IntegerField(default=0)
    felodipineer = models.IntegerField(default=0)
    fenofibrate = models.IntegerField(default=0)
    fentanyl = models.IntegerField(default=0)
    finasteride = models.IntegerField(default=0)
    floventhfa = models.IntegerField(default=0)
    fluconazole = models.IntegerField(default=0)
    fluoxetinehcl = models.IntegerField(default=0)
    fluticasonepropionate = models.IntegerField(default=0)
    furosemide = models.IntegerField(default=0)
    gabapentin = models.IntegerField(default=0)
    gemfibrozil = models.IntegerField(default=0)
    glimepiride = models.IntegerField(default=0)
    glipizide = models.IntegerField(default=0)
    glipizideer = models.IntegerField(default=0)
    glipizidexl = models.IntegerField(default=0)
    glyburide = models.IntegerField(default=0)
    haloperidol = models.IntegerField(default=0)
    humalog = models.IntegerField(default=0)
    hydralazinehcl = models.IntegerField(default=0)
    hydrochlorothiazide = models.IntegerField(default=0)
    hydrocodoneacetaminophen = models.IntegerField(default=0)
    hydrocortisone = models.IntegerField(default=0)
    hydromorphonehcl = models.IntegerField(default=0)
    hydroxyzinehcl = models.IntegerField(default=0)
    ibandronatesodium = models.IntegerField(default=0)
    ibuprofen = models.IntegerField(default=0)
    insulinsyringe = models.IntegerField(default=0)
    ipratropiumbromide = models.IntegerField(default=0)
    irbesartan = models.IntegerField(default=0)
    isosorbidemononitrateer = models.IntegerField(default=0)
    jantoven = models.IntegerField(default=0)
    janumet = models.IntegerField(default=0)
    januvia = models.IntegerField(default=0)
    ketoconazole = models.IntegerField(default=0)
    klorcon10 = models.IntegerField(default=0)
    klorconm10 = models.IntegerField(default=0)
    klorconm20 = models.IntegerField(default=0)
    labetalolhcl = models.IntegerField(default=0)
    lactulose = models.IntegerField(default=0)
    lamotrigine = models.IntegerField(default=0)
    lansoprazole = models.IntegerField(default=0)
    lantus = models.IntegerField(default=0)
    lantussolostar = models.IntegerField(default=0)
    latanoprost = models.IntegerField(default=0)

    class Meta:
        db_table = "pd_prescriber"

    def __str__(self):
        return (self.lname, ", ", self.fname)


class StateData(models.Model):
    state = models.CharField(max_length=14)
    stateabbrev = models.CharField(max_length=2)
    population = models.IntegerField(default=0)
    death = models.IntegerField(default=0)

    class Meta:
        db_table = "pd_statedata"

    def __str__(self):
        return (self.state)

class Triple(models.Model):
    prescriberid = models.ForeignKey(Prescriber, default="", verbose_name="PrescriberID", on_delete=models.DO_NOTHING, to_field='prescriberid')
    drugname = models.ForeignKey(Drug, default="", verbose_name="Category", on_delete=models.DO_NOTHING, to_field='drugname')
    qty = models.IntegerField(default=0)

    class Meta:
        db_table = 'pd_triple'

